Customer
britalodev/codenationMapFood pull request #11
Opened 2019-03-06 23:09 UTC by Tailac

2019-03-07 10:54 UTC, LuanPSantos requested changes

2019-03-07 10:54 UTC, LuanPSantos commented on src/main/java/br/com/movile/customer/model/Customer.java
> +	public String getId() {
Utilize o lombok para os getters e setters

2019-03-07 10:54 UTC, LuanPSantos commented on src/test/java/br/com/movile/Customer/Controller/CustomerIntegrationTest.java
> +		customerRepository.deleteAll();
Não é necessário. Para cada teste o banco e refeito automaticamente

2019-03-08 11:49 UTC, Tailac commented on src/main/java/br/com/movile/customer/model/Customer.java
> +	public String getId() {
blz, vou mudar

2019-03-08 16:19 UTC, LuanPSantos approved these changes

2019-03-08 16:26 UTC, merged