Order
britalodev/codenationMapFood pull request #7
Opened 2019-02-27 20:27 UTC by victormazevedo

2019-02-28 02:29 UTC, LuanPSantos requested changes

2019-02-28 02:29 UTC, LuanPSantos commented on src/main/java/br/com/movile/order/repository/OrderRepository.java
> +    Order findById(ObjectId orderId);
Como está o ID da entidade Order? Se for ObjectId então mude o segundo parametro de MongoRepository para ObjectId. Dessa forma, você não precisará criar um findById.

MongoRepository<Order, ObjectId >

2019-02-28 02:29 UTC, LuanPSantos commented on src/main/java/br/com/movile/order/service/OrderService.java
> +    public OrderService(OrderRepository orderRepository, RestaurantRepository restaurantRepository, CustomerRepository customerRepository, ItemRepository itemRepository) {
Eu nunca vi nada sobre isso, mas tem uma coisa que me coça quando eu vejo repositories de outro domínio injetados em outros services. Pra mim o correto seria UM repository por sevice (OrderService com apenas OrderRepository), e se um service precisar de uma consulta externa, ele acessa através do service do outro domínio.

2019-02-28 02:29 UTC, LuanPSantos commented on src/main/java/br/com/movile/order/service/OrderService.java
> +        Order order = orderRepository.findById(orderId);
Quando você resolver o problema do Repository (findById), poderá usar uma solução mais elegante para tratar um null com java 8.

2019-02-28 15:23 UTC, victormazevedo commented on src/main/java/br/com/movile/order/service/OrderService.java
> +    public OrderService(OrderRepository orderRepository, RestaurantRepository restaurantRepository, CustomerRepository customerRepository, ItemRepository itemRepository) {
Acho melhor por enquanto mantermos assim e mais pra frente vemos se vamos precisar refatorar ou não.

2019-02-28 15:34 UTC, victormazevedo commented
Novas alterações:

- preferi manter `MongoRepository<Order, String>` pois fiz uma alteração no Controller, em `getOrder`, para receber uma String e não mais um ObjectId. Fiz isso pois caso seja feito um GET com um ID fora do padrão do ObjectId, uma Exception é lançada antes mesmo de chegar em `OrderService`

- segunda mudança: sabendo dessa exception lançada, decidi tratá-la em `OrderService`. Por isso inclui um try-catch na conversão de String para ObjectId. De todo o caso, também alterei o retorno para uma forma mais legível e eficiente utilizando o Java8. Além da Exception da String estar fora do padráo de ObjectId, também tratei caso esteja no padrão mas não encontramos no mongodb.

2019-03-01 15:45 UTC, LuanPSantos approved these changes

2019-03-07 10:59 UTC, LuanPSantos approved these changes

2019-03-07 10:59 UTC, merged