Cordenadas
britalodev/codenationMapFood pull request #9
Opened 2019-03-05 13:44 UTC by britalodev

Fiz algumas alterações na busca pelo motoboy que estão funcionais, agr necessito que verifiquem e realizem o PR.

Agradecido.

2019-03-05 23:40 UTC, LuanPSantos requested changes

2019-03-05 23:40 UTC, LuanPSantos commented on pom.xml.orig
> +<<<<<<< HEAD
Conflito!

2019-03-05 23:40 UTC, LuanPSantos commented on src/main/java/br/com/movile/customer/controller/CustomerController.java
> +    public ResponseEntity<Customer> insert(@RequestBody Customer customer){
Ficou acordado no grupo que não seria usado o ResponseEntity

2019-03-05 23:40 UTC, LuanPSantos commented on src/main/java/br/com/movile/customer/model/Customer.java.orig
> +<<<<<<< HEAD
Conflito

2019-03-05 23:40 UTC, LuanPSantos commented on src/main/java/br/com/movile/customer/service/CustomerService.java.orig
> +<<<<<<< HEAD
Conflito

2019-03-05 23:40 UTC, LuanPSantos commented on src/main/java/br/com/movile/item/controller/ItemController.java
> +	@GetMapping("/id/{id}")
Não faz sentido /id/{id}. Não está sendo feita uma busca de IDs.

2019-03-05 23:40 UTC, LuanPSantos commented on src/main/java/br/com/movile/item/controller/ItemController.java
> +	@GetMapping("/descriptions/{description}")
Mesmo caso do ID.
Ainda sobre esse e os demais métodos abaixo, entendo como que esses métodos são busca de forma filtrada. para informar parâmetros de filtro é melhor utilizar RequestParams que sejam opcionais, ou seja, se eu quero pesquisar por "decription" e "restaurant" ao mesmo tempo, isso deve ser possível. Crie algo como 

GET /mapfood/items?description=japonesa&restaurant=orien

2019-03-05 23:40 UTC, LuanPSantos commented on src/main/java/br/com/movile/item/model/Item.java
> +	public String getId() {
Não está sendo usado o lombok

2019-03-05 23:40 UTC, LuanPSantos commented on src/main/java/br/com/movile/item/repository/ItemRepository.java
> +	List<Item> findByDescriptionLike(String description);
Para acompanhar a mudança nos Controllers, aqui vai ser necessário uma query dinâmica. Em SQL existe o query by example, talvez possa existir algo parecido em NoSQL

2019-03-06 18:37 UTC, victormazevedo commented on src/main/java/br/com/movile/item/controller/ItemController.java
> +	@GetMapping("/id/{id}")
Acredito que como se trata do Controller de Items, o melhor seria algo como
`@GetMapping("/{id}")`

2019-03-07 23:53 UTC, closed without merging